name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm test
    
  pr-review:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Send PR data to webhook for code review
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // Log basic info
          console.log('PR Number:', context.issue.number);
          console.log('Repo:', context.repo.owner + '/' + context.repo.repo);
          
          try {
            // Get PR details
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // Get PR files
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            console.log('Files changed:', files.data.length);
            
            // Debug auth setup
            const username = '${{ secrets.WEBHOOK_USERNAME }}';
            const password = '${{ secrets.WEBHOOK_AUTH_TOKEN }}';
            const webhookUrl = '${{ vars.WEBHOOK_URL }}';
            
            console.log('Username present:', username ? 'Yes' : 'No');
            console.log('Password present:', password ? 'Yes' : 'No');
            console.log('Webhook URL present:', webhookUrl ? 'Yes' : 'No');
            
            // Create basic auth and make request
            const auth = Buffer.from(`${username}:${password}`).toString('base64');
            
            // Build PR data payload
            const prData = {
              number: pr.data.number,
              title: pr.data.title,
              repository: {
                name: context.repo.repo,
                owner: context.repo.owner
              },
              files_count: files.data.length
            };
            
            console.log('Sending data to webhook...');
            
            // Use https request
            const https = require('https');
            let url;
            
            try {
              url = new URL(webhookUrl);
              console.log('Webhook URL parsed successfully');
            } catch (error) {
              console.error('Invalid webhook URL:', webhookUrl);
              throw new Error('Invalid webhook URL');
            }
            
            const options = {
              hostname: url.hostname,
              port: url.port || 443,
              path: url.pathname,
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Basic ${auth}`
              }
            };
            
            // Make the request
            const req = https.request(options, (res) => {
              console.log('Response status code:', res.statusCode);
              
              let data = '';
              res.on('data', (chunk) => {
                data += chunk;
              });
              
              res.on('end', () => {
                console.log('Response body:', data.substring(0, 200));
                
                if (res.statusCode >= 200 && res.statusCode < 300) {
                  console.log('Successfully sent PR data to webhook');
                } else {
                  console.error('Request failed with status code:', res.statusCode);
                  console.error('Failed to send PR data to webhook');
                }
              });
            });
            
            req.on('error', (error) => {
              console.error('Error sending request:', error.message);
              console.error('Network error when sending to webhook');
            });
            
            req.write(JSON.stringify(prData));
            req.end();
            
          } catch (error) {
            console.error('Error:', error.message);
            console.error('Failed to process PR data: ' + error.message);
          }
